### ISSUE TITLE
Update SampleDataUtil.java

### ISSUE THREAD

**Issue by ChengSashankh** [CS2103JAN2018-W11-B3/main#158]
## Update the links:
- This is important because it will look like a bug because right now on starting the jar it shows a black box when you use view command some times
- Update the links to our github profiles
- Alternatively, create one dummy github account, and point all links to them so that it behaves as expected.

## Add sample interviews to the data as well:
- This will better demonstrate the application's use to the graders when they open the application.

Thanks!

**Comment by deeheenguyen** [comment]
I think every sample data util has the init link, so the sample will link to google (I will change to our github profiles).
